bf16: true
cutoff_len: 1024
dataset: 13crop
ddp_timeout: 180000000
do_train: true
eval_steps: 500
eval_strategy: steps
finetuning_type: freeze
freeze_trainable_layers: 2
freeze_trainable_modules: all
gradient_accumulation_steps: 8
learning_rate: 5.0e-05
logging_steps: 5
lr_scheduler_type: cosine
max_grad_norm: 1.0
max_samples: 100000
model_name_or_path: D:\student\lzy\CDIP-ChatGLM3\model\LLM_Models\ChatGLM3_6B
num_train_epochs: 20.0
optim: adamw_torch
output_dir: D:\student\lzy\CDIP-ChatGLM3\model\LLM_Models\Freeze20
overwrite_cache: true
overwrite_output_dir: true
per_device_eval_batch_size: 1
per_device_train_batch_size: 2
plot_loss: true
preprocessing_num_workers: 16
save_steps: 5000
stage: sft
template: llama3
use_llama_pro: true
val_size: 0.1
warmup_ratio: 0.1
warmup_steps: 0
